Fix build on OSX
ruben@wodan: burp (master=)$ make check
  CC       src/server/protocol1/vss_strip.o
In file included from src/server/protocol1/vss_strip.c:1:
src/server/protocol1/../../burp.h:69:10: fatal error: 'openssl/ssl.h'
file not found
         ^
1 error generated.
make: *** [src/server/protocol1/vss_strip.o] Error 1

vss_strip.c includes burp.h, which includes openssl/ssl.h

Since openssl/ssl.h is not in the standard include path,
we need to add it to vss_strips CPPFLAGS.